---
all:
  hosts:
    horrea:
    oculus:
    localhost:
      ansible_connection: local
    # wsl is configured to use "mirrored" networking,
    # so reference the windows host name; not the linux hostname
    surface:
