---
- name: Configure Chrony NTP Server on Arch Linux (IoT Only)
  hosts: oculus
  become: true
  tasks:

    - name: Install chrony via pacman
      community.general.pacman:
        name: chrony

    - name: Disable and stop systemd-timesyncd
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: stopped
        enabled: false

    - name: Ensure timedatectl NTP synchronization is disabled for timesyncd
      ansible.builtin.command: timedatectl set-ntp false
      changed_when: false

    - name: Configure Chrony to allow the IPv4 IoT subnet exclusively
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        line: "allow 192.168.69.0/24"
        state: present
        insertafter: EOF
      notify: Restart Chrony

    - name: Enable and start chronyd service
      ansible.builtin.systemd:
        name: chronyd.service
        state: started
        enabled: true

  handlers:
    - name: Restart Chrony
      ansible.builtin.systemd:
        name: chronyd.service
        state: restarted