---
- name: Install Syncthing
  hosts: surface
  become: true
  tasks:
    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - curl
          - gpg
          - python3-lxml
        state: present
        update_cache: true

    - name: Add Syncthing APT signing key
      ansible.builtin.get_url:
        url: https://syncthing.net/release-key.gpg
        dest: /usr/share/keyrings/syncthing-archive-keyring.gpg

    - name: Add Syncthing APT repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg]
          https://apt.syncthing.net/ syncthing stable
        filename: syncthing
        state: present

    - name: Install Syncthing package
      ansible.builtin.apt:
        name: syncthing
        state: present
        update_cache: true

- name: Configure syncthing for marcus
  hosts: surface
  tasks:
    - name: Enable and start syncthing user service
      ansible.builtin.systemd:
        name: syncthing.service
        enabled: true
        state: started
        scope: user

- name: Configure Syncthing via REST API
  hosts: surface
  roles:
    - syncthing_folders
