---
- name: Install Syncthing
  hosts: tabula
  become: true
  tasks:
    - name: Install required dependencies
      ansible.builtin.pacman:
        name:
          - python-lxml
          - syncthing

- name: Configure syncthing for marcus
  hosts: tabula
  tasks:
    - name: Enable and start syncthing user service
      ansible.builtin.systemd:
        name: syncthing.service
        enabled: true
        state: started
        scope: user

- name: Configure Syncthing via REST API
  hosts: tabula
  roles:
    - syncthing_folders
