---
- name: Install borgmatic package
  hosts: horrea
  become: true
  tasks:
    - name: Install borgmatic package
      ansible.builtin.pacman:
        name: borgmatic

- name: Configure borgmatic user settings
  hosts: horrea
  vars_prompt:
    - name: borg_passphrase
      prompt: "Borg Passphrase"
      private: yes
  tasks:
    - name: Ensure borgmatic config directory exists
      ansible.builtin.file:
        path: /home/marcus/.config/borgmatic
        state: directory

    - name: Deploy borgmatic configuration from template
      ansible.builtin.template:
        src: borgmatic_config.yml.j2
        dest: /home/marcus/.config/borgmatic/config.yaml

    - name: Initialize borgmatic repositories
      ansible.builtin.command: borgmatic repo-create
      environment:
        BORG_PASSPHRASE: "{{ borg_passphrase }}"
      register: repo_create_result
      changed_when: repo_create_result.stderr != ""
      no_log: true
