---
- name: Install syncthing package
  hosts: horrea
  become: true
  tasks:
    - name: Install syncthing and python-lxml packages
      ansible.builtin.pacman:
        name:
          - syncthing
          - python-lxml

    - name: Enable lingering for marcus
      become: true
      ansible.builtin.command:
        cmd: loginctl enable-linger marcus
      args:
        creates: /var/lib/systemd/linger/marcus

- name: Configure syncthing for marcus
  hosts: horrea
  tasks:
    - name: Generate syncthing config if missing
      ansible.builtin.command:
        cmd: syncthing generate
      args:
        creates: "/home/marcus/.local/state/syncthing/config.xml"

    - name: Set Syncthing GUI to listen on all interfaces
      community.general.xml:
        path: "/home/marcus/.local/state/syncthing/config.xml"
        xpath: /configuration/gui/address
        value: 0.0.0.0:8384

    - name: Enable and start syncthing user service
      ansible.builtin.systemd:
        name: syncthing.service
        enabled: true
        state: started
        scope: user

- name: Test Syncthing REST API
  hosts: horrea
  vars:
    # we are still just doing testing, so it's fine to hard-code and have in source control
    syncthing_api_key: "7LuwxNoGE9noqcz2fLXAUiEEfDr5SU2u"
  tasks:
    - name: Fetch Syncthing config via REST API
      ansible.builtin.uri:
        url: "http://localhost:8384/rest/config"
        method: GET
        headers:
          X-API-Key: "{{ syncthing_api_key }}"
        return_content: true
      register: syncthing_config

    # - name: Display Syncthing config response
    #   ansible.builtin.debug:
    #     var: syncthing_config.json

    - name: Add backup folders via REST API
      ansible.builtin.uri:
        url: "http://localhost:8384/rest/config/folders"
        method: POST
        headers:
          X-API-Key: "{{ syncthing_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          id: "{{ item | basename }}"
          path: "{{ item | basename }}"
        status_code: 200
      loop: "{{ backup_dirs }}"
      when: "(item | basename) not in (syncthing_config.json.folders | map(attribute='id') | list)"
